[package]
name = "database"
version = "0.1.0"
edition = "2021"

[features]
memory = []

[dependencies]
async-trait = "0.1.79"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["macros", "sync"] }
tracing = "0.1.40"
